# After changing this file, check it on:
#   http://lint.travis-ci.org/

os:         linux
sudo:       false

language:   python

python:
    - 3.6

env:
    global:
        - TRAVIS_CK_WHICH_TEST=hello
        - TRAVIS_CK_CXX_COMPILER=gcc
    matrix:
        - TRAVIS_CK_WHICH_TEST=hello TRAVIS_CK_USE_BACKEND=local_clifford_simulator
        - TRAVIS_CK_WHICH_TEST=hello TRAVIS_CK_USE_BACKEND=local_unitary_simulator
        - TRAVIS_CK_WHICH_TEST=hello TRAVIS_CK_USE_BACKEND=local_qiskit_simulator
        - TRAVIS_CK_WHICH_TEST=hello TRAVIS_CK_USE_BACKEND=local_qasm_simulator
        - TRAVIS_CK_WHICH_TEST=vqe_hydrogen TRAVIS_CK_USE_BACKEND=local_qasm_simulator

matrix:
    include:
        - os: osx
          osx_image: xcode9.2
          language: generic
          python:   3.7
          env:      TRAVIS_CK_WHICH_TEST=hello TRAVIS_CK_USE_BACKEND=local_clifford_simulator WANTED_PYTHON_VERSION=3.7
        - os: osx
          osx_image: xcode9.2
          language: generic
          python:   3.7
          env:      TRAVIS_CK_WHICH_TEST=hello TRAVIS_CK_USE_BACKEND=local_unitary_simulator WANTED_PYTHON_VERSION=3.7
        - os: osx
          osx_image: xcode9.2
          language: generic
          python:   3.7
          env:      TRAVIS_CK_WHICH_TEST=hello TRAVIS_CK_USE_BACKEND=local_qiskit_simulator WANTED_PYTHON_VERSION=3.7
        - os: osx
          osx_image: xcode9.2
          language: generic
          python:   3.7
          env:      TRAVIS_CK_WHICH_TEST=hello TRAVIS_CK_USE_BACKEND=local_qasm_simulator WANTED_PYTHON_VERSION=3.7
        - os: osx
          osx_image: xcode9.2
          language: generic
          python:   3.7
          env:      TRAVIS_CK_WHICH_TEST=vqe_hydrogen TRAVIS_CK_USE_BACKEND=local_qasm_simulator WANTED_PYTHON_VERSION=3.7

addons:
    apt:
        packages:
            - g++-6                                                             # For C++14 we need at least gcc-6
            - python-pip
            - libblas-dev
            - liblapack-dev
        sources:
            - ubuntu-toolchain-r-test

before_install:
    - |
        if [ $TRAVIS_OS_NAME == "osx" ]; then
            brew update                                                         # this swaps python versions and makes 3 the default one

            brew install freetype                                               # somehow needed for matplotlib which is not needed!

            brew reinstall python                                               # install and link python3 and pip3 to /usr/local/bin
            export PATH=/usr/local/opt/python/bin:$PATH
            export PYTHON_EXE=python3

            if [ "$TRAVIS_CK_CXX_COMPILER" == "llvm" ]; then
                brew install llvm\@5
                export TRAVIS_CK_COMPILER_CHOICE="Version 5"
            elif [ "$TRAVIS_CK_CXX_COMPILER" == "gcc" ]; then
                brew install gcc\@7 || brew link --overwrite gcc\@7             # to avoid symlink conflict with oclint
                export TRAVIS_CK_COMPILER_CHOICE="Version 7"
            fi

            export CK_PLATFORM_NAME="generic-macos "                            # Select CK platform
        else
            export CK_PLATFORM_NAME="generic-linux "                            # Select CK platform (note the trailing space to make the choice unique)
            export PYTHON_EXE=python
            export TRAVIS_CK_COMPILER_CHOICE="Version 6"
        fi

install:
    - CWD=`pwd`
    - THIS_REPO_NAME=`basename $CWD`
    - echo "os=${TRAVIS_OS_NAME}, python=${TRAVIS_PYTHON_VERSION}, compiler=${TRAVIS_CK_CXX_COMPILER}, backend=${TRAVIS_CK_USE_BACKEND}, which_test=${TRAVIS_CK_WHICH_TEST}"
    - echo "CWD=${CWD}, THIS_REPO_NAME=${THIS_REPO_NAME}, PATH=${PATH}"
    - which ${PYTHON_EXE}
    - ${PYTHON_EXE} --version
    - rm -f `which pip`                                                         # the file is removable, but not writeable
    - ${PYTHON_EXE} -m pip install --ignore-installed --verbose pip setuptools  # make sure pip is also up to date no matter what
    - ${PYTHON_EXE} -m pip install -r requirements.txt                          # ck kernel itself and some essential components
    - ck pull repo:${THIS_REPO_NAME}                                            # ...also trigger pulling dependent repositories
    - echo "$CK_PLATFORM_NAME" | ck detect platform.os --update_platform_init   # set the platform to generic-linux (1) or generic-macos (2)
    -       ck detect soft:compiler.python --full_path=`which ${PYTHON_EXE}`    # pick the one Travis has set for us in the PATH
    - SCIPY=`python -m pip show scipy | awk '$1=="Location:" {print $2}'`/scipy/__init__.py
    - ck detect soft:lib.python.scipy --full_path=$SCIPY                        # pick the one installed via requirements.txt
    - echo "$TRAVIS_CK_COMPILER_CHOICE" | ck detect soft:compiler.${TRAVIS_CK_CXX_COMPILER}     # force detection of a specific C/C++ compiler
    - echo   | ck detect soft:lib.blas
    - echo   | ck detect soft:lib.lapack
    -          ck install package:lib-qiskit-0.5.4                              # Fix the version


script:
    - |
        if [ $TRAVIS_CK_WHICH_TEST == "vqe_hydrogen" ]; then
            ck deploy_optimizer vqe --value=optimizer.cobyla
            ck deploy_ansatz vqe --value=ansatz.tiny2
            ck run program:qiskit-vqe --env.VQE_MAX_ITERATIONS=10 --env.VQE_QUANTUM_BACKEND=${TRAVIS_CK_USE_BACKEND}
        else
            ck run program:qiskit-demo --cmd_key=${TRAVIS_CK_WHICH_TEST} --env.CK_IBM_BACKEND=${TRAVIS_CK_USE_BACKEND}
        fi
